version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      MONGO_URI: mongodb://db:27017/london_houses

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

