name: Push Notification
on:
  push:
    branches: [main]

jobs:
  push_notification:
  runs-on: ubuntu-latest
  steps:
      - name: Notify on push
        uses: DuyguMazak/repository-dispatch@v1
        with:
          event-type: "push"
          client-payload: '{"pusher": "${{github.event.pusher.name}}", "ref": "${{github.event.ref }}", "sha": "${{github.event.after}}"}'