name: Simple Action
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Building the project..."
          # Add your build commands

      - name: Test
        run: |
          echo "Running tests..."
          # Add your test commands 